### ISSUE TITLE
Dependency to RAK

### ISSUE THREAD

**Issue by ghost** [vivien/notes#2]
Please mention in the README that there is a dependency on RAK, the ruby grep tool.

On first run my error was:

  /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- rak (LoadError)  

Thank you.

**Comment by vivien** [comment]
I guess you tried from source because you shouldn't have any problem while installing notes from rubygems, as rak is listed as a dependency.

The README file is updated. Note: the gem was broken with the just released new rak version, so I've pushed a 0.0.3 version of notes. BTW, I'm refactoring notes. New version coming soon. Keep in touch ;)

Thanks for the comment!
